-- Wave E: IMPACT supplier key + mapping-related ExceptionCase types
-- Additive only; no data backfill.

ALTER TYPE "SupplierKey" ADD VALUE IF NOT EXISTS 'IMPACT';

ALTER TYPE "ExceptionCaseType" ADD VALUE IF NOT EXISTS 'MAPPING_REQUIRED_FIELD_MISSING';
ALTER TYPE "ExceptionCaseType" ADD VALUE IF NOT EXISTS 'MAPPING_INVALID_VALUE';
ALTER TYPE "ExceptionCaseType" ADD VALUE IF NOT EXISTS 'MAPPING_UNKNOWN_ENUM';
ALTER TYPE "ExceptionCaseType" ADD VALUE IF NOT EXISTS 'MAPPING_UNMAPPED_CRITICAL_FIELD';
ALTER TYPE "ExceptionCaseType" ADD VALUE IF NOT EXISTS 'MAPPING_CONFLICT';
