export const DEFAULT_COUPON_COLUMNS = [
  {
    key: "brandName",
    label: "Brand Name",
    sortOrder: 0,
    visible: true,
    sourceType: "builtin",
    builtinKey: "brandName",
    optimisePaths: ["companyName"],
    boostinyPaths: ["campaign.name", "campaign"],
    trackierPaths: ["campaign_name", "campaignName", "campaign.name"],
    columnType: "text",
  },
  {
    key: "campaignName",
    label: "Campaign Name",
    sortOrder: 1,
    visible: true,
    sourceType: "builtin",
    builtinKey: "campaignName",
    optimisePaths: ["campaignName", "campaign_name"],
    boostinyPaths: ["campaign_name"],
    trackierPaths: ["campaign_name", "campaignName"],
    columnType: "text",
  },
  {
    key: "categoryName",
    label: "Category Name",
    sortOrder: 2,
    visible: true,
    sourceType: "builtin",
    builtinKey: "categoryName",
    optimisePaths: ["categoryName"],
    boostinyPaths: [],
    trackierPaths: ["category_name", "categoryName"],
    columnType: "text",
  },
  {
    key: "couponCode",
    label: "Coupon Code",
    sortOrder: 3,
    visible: true,
    sourceType: "builtin",
    builtinKey: "couponCode",
    optimisePaths: [],
    boostinyPaths: [],
    columnType: "text",
  },
  {
    key: "couponLink",
    label: "Coupon Link",
    sortOrder: 4,
    visible: true,
    sourceType: "builtin",
    builtinKey: "couponLink",
    optimisePaths: [],
    boostinyPaths: [],
    columnType: "text",
  },
  {
    key: "codeType",
    label: "Coupon Type",
    sortOrder: 5,
    visible: true,
    sourceType: "builtin",
    builtinKey: "codeType",
    optimisePaths: [],
    boostinyPaths: [],
    columnType: "text",
  },
  {
    key: "discountPercentage",
    label: "Discount Percentage",
    sortOrder: 6,
    visible: true,
    sourceType: "builtin",
    builtinKey: "discountPercentage",
    optimisePaths: ["discount"],
    boostinyPaths: ["ad_set"],
    trackierPaths: ["description", "discount"],
    columnType: "text",
  },
  {
    key: "startDate",
    label: "Start Date",
    sortOrder: 7,
    visible: true,
    sourceType: "builtin",
    builtinKey: "startDate",
    optimisePaths: ["activationDate"],
    boostinyPaths: ["start_date"],
    trackierPaths: ["start", "start_date", "startDate"],
    columnType: "date",
  },
  {
    key: "expiryDate",
    label: "Expiry Date",
    sortOrder: 8,
    visible: true,
    sourceType: "builtin",
    builtinKey: "expiryDate",
    optimisePaths: ["expiryDate"],
    boostinyPaths: ["expiry"],
    trackierPaths: ["end", "expiry", "expiryDate"],
    columnType: "date",
  },
  {
    key: "couponStatus",
    label: "Coupon Status",
    sortOrder: 9,
    visible: true,
    sourceType: "builtin",
    builtinKey: "couponStatus",
    optimisePaths: ["status"],
    boostinyPaths: [],
    trackierPaths: ["status"],
    columnType: "text",
  },
  {
    key: "campaignStatus",
    label: "Campaign Status",
    sortOrder: 10,
    visible: true,
    sourceType: "builtin",
    builtinKey: "campaignStatus",
    optimisePaths: [],
    boostinyPaths: [],
    trackierPaths: [],
    columnType: "text",
  },
  {
    key: "networkSource",
    label: "Network Source",
    sortOrder: 11,
    visible: true,
    sourceType: "builtin",
    builtinKey: "networkSource",
    optimisePaths: [],
    boostinyPaths: [],
    columnType: "text",
  },
];
