export const PERMISSIONS = {
  CAMPAIGNS_READ: "campaigns:read",
  PERFORMANCE_READ: "performance:read",
  PAYMENTS_READ: "payments:read",
  CONVERSIONS_READ: "conversions:read",
  COMMISSION_READ: "commission:read",
  EXPORT_DATA: "export:data",
  INTEGRATIONS_READ: "integrations:read",
  INTEGRATIONS_MANAGE: "integrations:manage",
  SYNC_TRIGGER: "sync:trigger",
  USERS_MANAGE: "users:manage",
  LOGS_READ: "logs:read",
  SYSTEM_READ: "system:read",
  COUPONS_READ: "coupons:read",
  COUPONS_WRITE: "coupons:write",
  COUPON_COLUMNS_MANAGE: "coupon_columns:manage",
  MERCHANTS_READ: "merchants:read",
  MERCHANTS_MANAGE: "merchants:manage",
  CATALOG_READ: "catalog:read",
  CATALOG_MANAGE: "catalog:manage",
  CLIENTS_READ: "clients:read",
  CLIENTS_MANAGE: "clients:manage",
  TRACKING_READ: "tracking:read",
  TRACKING_MANAGE: "tracking:manage",
  COUPON_ASSIGN_READ: "coupon:read",
  COUPON_ASSIGN_MANAGE: "coupon:manage",
  COMMISSION_MANAGE: "commission:manage",
  OPS_READ: "ops:read",
  OPS_MANAGE: "ops:manage",
  EXCEPTIONS_READ: "exceptions:read",
  EXCEPTIONS_MANAGE: "exceptions:manage",
  FINANCE_OPS_READ: "finance_ops:read",
  PRODUCTS_READ: "products:read",
  PORTAL_CAMPAIGNS_READ: "portal:campaigns:read",
  PORTAL_PERFORMANCE_READ: "portal:performance:read",
  PORTAL_PAYMENTS_READ: "portal:payments:read",
  PORTAL_PAYMENTS_MANAGE: "portal:payments:manage",
  PORTAL_SETTINGS_READ: "portal:settings:read",
  PORTAL_SUPPORT: "portal:support",
};

export const USER_ROLES = ["ADMIN", "OPERATIONS", "ANALYST", "TECH", "SUPPORT", "CLIENT"];
export const STAFF_USER_ROLES = ["ADMIN", "OPERATIONS", "ANALYST", "TECH", "SUPPORT"];

export const ROLE_PERMISSIONS = {
  ADMIN: Object.values(PERMISSIONS),
  OPERATIONS: [
    PERMISSIONS.CAMPAIGNS_READ,
    PERMISSIONS.PERFORMANCE_READ,
    PERMISSIONS.PAYMENTS_READ,
    PERMISSIONS.CONVERSIONS_READ,
    PERMISSIONS.COMMISSION_READ,
    PERMISSIONS.EXPORT_DATA,
    PERMISSIONS.COUPONS_READ,
    PERMISSIONS.COUPONS_WRITE,
    PERMISSIONS.SYSTEM_READ,
    PERMISSIONS.MERCHANTS_READ,
    PERMISSIONS.MERCHANTS_MANAGE,
    PERMISSIONS.CATALOG_READ,
    PERMISSIONS.CATALOG_MANAGE,
    PERMISSIONS.CLIENTS_READ,
    PERMISSIONS.CLIENTS_MANAGE,
    PERMISSIONS.TRACKING_READ,
    PERMISSIONS.TRACKING_MANAGE,
    PERMISSIONS.COUPON_ASSIGN_READ,
    PERMISSIONS.COUPON_ASSIGN_MANAGE,
    PERMISSIONS.COMMISSION_MANAGE,
    PERMISSIONS.OPS_READ,
    PERMISSIONS.OPS_MANAGE,
    PERMISSIONS.EXCEPTIONS_READ,
    PERMISSIONS.EXCEPTIONS_MANAGE,
    PERMISSIONS.FINANCE_OPS_READ,
    PERMISSIONS.PRODUCTS_READ,
  ],
  ANALYST: [
    PERMISSIONS.CAMPAIGNS_READ,
    PERMISSIONS.PERFORMANCE_READ,
    PERMISSIONS.CONVERSIONS_READ,
    PERMISSIONS.EXPORT_DATA,
    PERMISSIONS.COUPONS_READ,
    PERMISSIONS.MERCHANTS_READ,
    PERMISSIONS.CATALOG_READ,
    PERMISSIONS.CLIENTS_READ,
    PERMISSIONS.TRACKING_READ,
    PERMISSIONS.COUPON_ASSIGN_READ,
    PERMISSIONS.EXCEPTIONS_READ,
    PERMISSIONS.PRODUCTS_READ,
  ],
  TECH: [
    PERMISSIONS.CAMPAIGNS_READ,
    PERMISSIONS.INTEGRATIONS_READ,
    PERMISSIONS.INTEGRATIONS_MANAGE,
    PERMISSIONS.SYNC_TRIGGER,
    PERMISSIONS.LOGS_READ,
    PERMISSIONS.SYSTEM_READ,
    PERMISSIONS.OPS_READ,
    PERMISSIONS.EXCEPTIONS_READ,
    PERMISSIONS.PRODUCTS_READ,
  ],
  SUPPORT: [
    PERMISSIONS.CAMPAIGNS_READ,
    PERMISSIONS.COUPONS_READ,
    PERMISSIONS.EXCEPTIONS_READ,
    PERMISSIONS.CLIENTS_READ,
  ],
  CLIENT: [
    PERMISSIONS.PORTAL_CAMPAIGNS_READ,
    PERMISSIONS.PORTAL_PERFORMANCE_READ,
    PERMISSIONS.PORTAL_PAYMENTS_READ,
    PERMISSIONS.PORTAL_PAYMENTS_MANAGE,
    PERMISSIONS.PORTAL_SETTINGS_READ,
    PERMISSIONS.PORTAL_SUPPORT,
  ],
};

export const ENTITY_TYPE_PERMISSIONS = {
  campaign: PERMISSIONS.CAMPAIGNS_READ,
  performance: PERMISSIONS.PERFORMANCE_READ,
  payment: PERMISSIONS.PAYMENTS_READ,
  conversion: PERMISSIONS.CONVERSIONS_READ,
  coupon: PERMISSIONS.COUPONS_READ,
};

export function getPermissionsForRole(role) {
  return ROLE_PERMISSIONS[role] || [];
}

export function roleHasPermission(role, permission) {
  return getPermissionsForRole(role).includes(permission);
}

export function roleHasAnyPermission(role, permissions) {
  const granted = getPermissionsForRole(role);
  return permissions.some((permission) => granted.includes(permission));
}
